# Generated by Django 4.1 on 2023-04-13 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="login_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.EmailField(max_length=254, unique=True)),
                ("email_otp", models.CharField(blank=True, max_length=6, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "dt_created",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 4, 13, 18, 6, 47, 545215)
                    ),
                ),
                (
                    "dt_updated",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 4, 13, 18, 6, 47, 545215)
                    ),
                ),
            ],
            options={
                "db_table": "login_details",
            },
        ),
    ]
