# Generated by Django 4.1 on 2023-04-13 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("otp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="login_details",
            name="is_verified",
        ),
        migrations.AddField(
            model_name="login_details",
            name="email_otp_used",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="login_details",
            name="dt_created",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 13, 21, 31, 50, 996154)
            ),
        ),
        migrations.AlterField(
            model_name="login_details",
            name="dt_updated",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 13, 21, 31, 50, 996154)
            ),
        ),
    ]
